;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_0

@sfx_ntsc_0:
	.byte $80,$bf,$81,$94,$82,$00,$01,$81,$7f,$01,$81,$74,$01,$81,$6a,$01
	.byte $81,$60,$01,$00
