;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_0
	.word @sfx_ntsc_1

@sfx_ntsc_0:
	.byte $80,$bf,$81,$94,$82,$00,$01,$81,$7f,$01,$81,$74,$01,$81,$6a,$01
	.byte $81,$60,$01,$00
@sfx_ntsc_1:
	.byte $80,$ff,$81,$26,$82,$02,$01,$81,$7c,$01,$81,$f3,$01,$81,$19,$82
	.byte $03,$01,$81,$d4,$82,$02,$01,$81,$7d,$01,$81,$1d,$01,$00
